name: katering_preorder
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Saran: Gunakan range ini agar lebih fleksibel

dependencies:
  flutter:
    sdk: flutter

  # --- Utilities ---
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  intl: any
  fl_chart: ^1.1.1

  # --- Localization ---
  flutter_localizations:
    sdk: flutter

  # --- Maps ---
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

  # --- Firebase ---
  # Pastikan versi firebase ini kompatibel satu sama lain
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1 # Saran: Beri versi spesifik agar aman

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
